README.md, src/main.rs
This patch adds pod metrics next to the node metrics already reported. The pod-specific metrics will have a dashboard separate from the host metrics one on AppSignal.com.
Merging this will require an updated container to be pushed.
=> Add pod metrics

Cargo.toml
By default, Rust doesn't strip the tags from the release artifacts. Set the `strip` config in release profile to true, which is the same as "symbols".
https://doc.rust-lang.org/cargo/reference/profiles.html#strip
This reduces the file size by a couple MB.
Without strip:
- amd64-unknown-linux-musl/appsignal-kubernetes: 13M
- arm64-unknown-linux-musl/appsignal-kubernetes: 12M
With strip:
- amd64-unknown-linux-musl/appsignal-kubernetes: 10M
- arm64-unknown-linux-musl/appsignal-kubernetes: 8.7M
Optimize the release artifact size further by enabling lto by setting the config option in the release profile to true, which is the same as "fat".
> Performs “fat” LTO which attempts to perform optimizations across all
> crates within the dependency graph. …
=> Reduce build artifact size

Dockerfile, Makefile, README.md
Some PRs cherry-picked from PR #4 to make it work locally.
---
In macOS, the `tr` command does not support long options (`--delete`) or character ranges (`a-z`). Since we seemingly intend to remove the `v` at the beginning of the tag name, let's do that.
This makes it easier to test them using Kubernetes on Docker Desktop.
This makes it easier to test if it works for both platforms without having to publish a new version, or publish a version to a test repository.
The alpine tag gets overwritten on every release of the rust image. Use a more specific tag that should change less or not at all to make sure we're always publishing from the same base.
Rust version based on the version selected in PR #4.
I noticed we ship the image with the `rust:alpine` image as a base. This means we ship the …
=> Reduce published Docker image size

Cargo.lock, Cargo.toml, Dockerfile, deployment.yaml, rust-toolchain.toml, src/main.rs
Requested by a customer; see [Intercom conversation](https://app.intercom.com/a/inbox/yzor8gyw/inbox/conversation/16410700363805) and [Slack conversation](https://appsignal.slack.com/archives/C7XHXQ7N0/p1727092126423819).
The project will not build on versions lower than `1.75.0`, due to
the `kube-derive` version it depends on.
Extract the volume metrics from each pod, if any.
Instead, write an error message to standard error, containing the
error obtained from the `run()` function, then loop again.
Do not emit metrics for a node, pod or volume if it doesn't have a
name. In practice, this only happens for volumes.
When a metric is missing, instead of emitting a metric with a value
of zero, do not emit a metric at all.
Re-structure the metric extraction functions to be able to test the
way …
=> Implement volume metrics

Dockerfile
Will merge without review for the 0.2.0 release.
---
When building for several platforms, both builds attempt to use the
same `target` cache volume. Not only does this essentially force the
builds to be sequential, as `cargo` takes a lock on the folder, but
the artifacts compiled for one platform cannot be re-used for the
other in future builds, in practice forcing the build to start from
scratch as if no cache were present.
Use the `id` mount attribute and the `$TARGETPLATFORM` environment
variable to have different cache volumes mounted in the same path
for each platform.
=> Use independent cache mounts per platform

Makefile, mono.yml, script/read_version.sh, script/write_version.sh
Adds Mono for the publishing process. Running `mono publish` will automatically bump up the version number according to the changesets, compile the changesets into a changelog and publish the package with the bumped version number.
=> Add Mono for publishing

Makefile
On my Intel machine, the ARM build gets stuck on building the final artifact, using 100% CPU and slowly increasing memory use forever.
I will look into sorting this out, but for now, being able to pass `PLATFORMS=linux/amd64` provides a workaround for testing it locally.
I have also made `TAG` into an environment variable as that allows for builds to be given different tags -- this makes it easier to check that your local Kubernetes isn't running a stale build.
=> Pass build platforms in environment variable

.github/workflows/ci.yaml, src/main.rs
- Ensure that the tests are also checked by clippy.
- Exit with an error code on warnings.
- Enable clippy for all targets.
- Test all the features (not that we have any, but it's good practice)
And fix most of the issues with `--fix`.
Clone the self value because it gets transformed into a new value.
While the original code works, it can create confusing situations about ownership if the AppsignalMetric is used after `to_key` is called.
Pointed out by clippy in this rule:
https://rust-lang.github.io/rust-clippy/master/index.html#/wrong_self_convention
=> Update clippy config in CI

src/main.rs
Leftover from https://github.com/appsignal/appsignal-kubernetes/pull/14.
In https://github.com/appsignal/appsignal-kubernetes/pull/13, the `.to_key` was modified to take `&self` as an argument
and clone it, following Clippy's (correct) recommendation for
`.to_key` methods to take `&self` as an argument.
However, we have no need in our codebase to use the metric after
converting it to a key, so this incurs a needless clone, which
could always be done explicitly if needed. Undo the change to the
method's signature, but rename it to `.into_key` to stay in line
with Clippy's `wrong_self_convention` lint rule.
=> Avoid cloning metrics into keys

src/main.rs
Timestamps were set for Node and Pod metrics. This patch adds a test to make sure that actually happened. Also, timestamps were added before the addition of the volume metrics. This patch adds timestamps to volume metrics as well. 
@matsimitsu could you double-check this? Unless I'm missing something we already had timestamps set on most metrics, except for the volume ones. This version should set timestamps for all metrics all the time.
Closes #19.
=> Ensure timestamps are set for all metrics

src/main.rs
Previously, the node names were wrapped in double quotes, as an artefact of their JSON roots. This patch makes sure the quotes are removed by converting the values to str before producing the string outputs.
Closes #20
=> Remove extra quotes around node names

src/main.rs
Instead of sending the network metrics as we get them, subtract the previous minute's value to get the minutely value. Currently, this only happens for the network metrics, but more metrics can be added if needed.
=> Use delta values for cumulative metrics

src/main.rs
This patch adds memory_usage, a combined field that's set for nodes by combining the memory_usage_bytes, memory_available_bytes and memory_rss_bytes fields. 
Closes https://github.com/appsignal/appsignal-kubernetes/issues/27
=> Add memory_usage as a percentage

src/main.rs
This patch adds swap, a combined field that's set for nodes by combining the swap_usage_bytes and swap_available_bytes fields.
=>  Add swap_usage as a percentage

.github/workflows/ci.yaml, Rakefile
To make sure any changes don't break the release builds, let's build them in the CI.
That way, we don't find out the build is broken when we try to run the release workflow.
I've reverted the `cargo test` commands to just run `cargo test` on the Ubuntu runner for now as we do in our other projects too.
We may want to revisit this, but let's first add the release build test steps.
=> Build each target on CI

.changesets/print-configuration-on-startup-to-aid-in-debugging.md, deployment.yaml, src/main.rs
This patch adds debug logging when the integration starts, and makes sure the log level is at least set to info.
=> Print configuration on startup to aid in debugging

.github/workflows/publish_release.yaml
This patch adds a call to gh release to create a new release after committing the changes to the repository.
=> Add release step to the publish workflow

.github/workflows/publish_release.yaml
The Helm chart releaser needs the Git remote to be a HTTPS URL.
We check out the repository with SSH using a deploy key at the start of the workflow, because any other workflows that depend on `push` events to trigger them need to be pushed with a deploy key.
Update the remote so it works with the Helm releaser again.
[skip ci]
=> Fix Git remote in publish workflow

.changesets/fix-pod-permissions.md, Cargo.lock, deployment.yaml
Update the `deployment.yaml` file to also request access to pods so we can fetch the pods list.
Fixes this error:
```
Failed to extract metrics: ApiError: pods is forbidden: User "system:serviceaccount:default:appsignal-kubernetes-service-account" cannot list resource "pods" in API group "" at the cluster scope: Forbidden (ErrorResponse { status: "Failure", message: "pods is forbidden: User \"system:serviceaccount:default:appsignal-kubernetes-service-account\" cannot list resource \"pods\" in API group \"\" at the cluster scope", reason: "Forbidden", code: 403 })
```
=> Fix pod permisions configuration

.github/workflows/publish_release.yaml
I noticed that after a release the Cargo.lock would be modified. This ensures it commits the updated version.
[skip review]
=> Commit all release file changes

.github/workflows/publish_release.yaml, README.md, Rakefile, charts/appsignal-kubernetes/Chart.yaml, charts/appsignal-kubernetes/templates/deployment.yaml, charts/appsignal-kubernetes/templates/namespace.yaml, charts/appsignal-kubernetes/values.yaml, deployment.yaml, script/write_version
Our existing Helm chart is just a copy and paste of the existing `deployment.yaml` for `kubectl`, with some unrelated broken files alongside it.
Replace this with templates that actually interpolate the values in the chart. Rather than having the release process copy-paste the `deployment.yaml` from the root into the chart, do the opposite: use Helm's template as the source of truth to generate `deployment.yaml` from.
Fixes #59.
=> Implement an actual Helm chart
